# IMPORTANT: For these settings to work, you MUST rename this file from 'netlify.txt' to 'netlify.toml'
[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

# Redirect rule for cleaner API paths. This maps requests from /api/*
# to the corresponding function in the netlify/functions directory.
# For example, a call to /api/initiate-case will be routed to
# /.netlify/functions/initiate-case.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
